[package]
name = "rdom"
description = "A Rust-based simulated DOM (browser-independent replacement for web_sys)"
repository = "https://github.com/philip-peterson/rust-rdom/"
version = "0.2.0"
authors = ["Philip Peterson <philip.c.peterson@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.3.0"
paste = "1.0.5"
quote = { version = "1.0.9", optional = true }
thiserror = "1"
sourcegen = "0.3.0"

[build-dependencies]
sourcegen-cli = "0.4.0"
quote = "1.0.9"
syn = "1.0.71"
anyhow = "1.0.40"
proc-macro2 = "1.0.26"
serde = "1.0.125"
serde_yaml = "0.8.17"
serde_derive = "1.0.125"