[package]
name = "rdom"
description = "A Rust-based simulated DOM (browser-independent replacement for web_sys)"
repository = "https://github.com/philip-peterson/rust-rdom/"
version = "0.2.0"
authors = ["Philip Peterson <philip.c.peterson@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.3.0"
log = "0.4.14"
paste = "1.0.5"
quote = "1.0.9"
thiserror = "1"
sourcegen = "0.3.0"
arc_new_cyclic_n = "1.0.1"
variadic_closure = "1.3.0"
destructure_traitobject = "0.2.0"
