[package]
name = "rdom-build"
version = "0.1.0"
authors = ["Maxim <maxim.kosterov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sourcegen-cli = "0.4.0"
quote = "1.0.9"
syn = "1.0.71"
anyhow = "1.0.40"
proc-macro2 = "1.0.26"
serde = "1.0.125"
serde_derive = "1.0.125"
lazy_static = "1.4.0"
toml = "0.5.8"
